### PR TITLE
Fix/fallback sequential for sync methods

### LINKED ISSUE #3186: [Bug] FallbackLayer breaks stateful RPC methods such as eth_sendRawTransactionSync due to parallel fan-out
### Component

transports

### What version of Alloy are you on?

1.1.0

### Operating System

macOS (Apple Silicon)

### Describe the bug

FallbackLayer performs parallel fan-out to all transports for every request.
This behavior is correct for idempotent/stateless RPC methods, but breaks stateful methods such as `eth_sendRawTransactionSync` (EIP-7966), or any other RPC with side effects or synchronous waiting semantics.

The result is incorrect responses, especially when handling "already known" errors, and violates the semantics of these RPCs.

## Problem

With multiple transports:
1. Transport A receives the tx, processes it, and returns a success receipt
2. Transport B receives the tx, but because the hash already exists, returns "already known"
3. "already known" returns faster and is not a transport error, so FallbackLayer picks it
4. The actual correct receipt from transport A is discarded
5. Client receives "already known" instead of the real receipt

This makes eth_sendRawTransactionSync unusable with FallbackLayer.

## Reproduction Steps
1. Configure FallbackLayer with two HTTP transports, connected to RPC endpoints implementing `eth_sendRawTransactionSync`
2. Submit a valid signed tx
3. Observe that Alloy returns "already known"

CC @Syzygy106 as you have contributed eth_sendRawTransactionSync recently.

### PR DESCRIPTION
**Pull request by Syzygy106**
## Motivation

Fixes #3186

The `FallbackLayer` implementation was using parallel fan-out for all RPC methods, which caused issues with methods that have non-deterministic results when executed concurrently across multiple nodes.

Specifically, `eth_sendRawTransactionSync` (EIP-7966) waits for a transaction receipt. When executed in parallel, for example:
- **Node A (slow)**: Processes the transaction and returns the receipt after 100ms
- **Node B (fast)**: Recognizes the transaction as "already known" and returns an error after 10ms

The `FallbackLayer` would incorrectly return the fast "already known" error instead of waiting for the actual receipt from the slower node.

## Solution

Introduced selective execution strategies based on result determinism:

1. **Added `requires_sequential_execution()` function** - Identifies RPC methods that return non-deterministic results when executed in parallel:
   - `eth_sendRawTransactionSync` (EIP-7966)
   - `eth_sendTransactionSync`

2. **Added `make_request_sequential()` method** - Implements sequential fallback that tries transports one-by-one until success, respecting the ranking system.

3. **Modified `make_request()`** - Routes non-deterministic methods to sequential execution while keeping parallel execution for all other methods (including `eth_sendRawTransaction`, which returns a deterministic transaction hash).

**Key Design Decision**: Not all stateful methods require sequential execution. Methods like `eth_sendRawTransaction` are stateful but return deterministic results (transaction hashes), making parallel execution safe and beneficial for performance.

### Representation - 
```text
/// # Before Fix (Parallel Execution):
/// Time       Transport A               Transport B
/// ─────────────────────────────────────────────────────────
/// 0ms        🚀 START                  🚀 START (parallel!)
///            │                         │
/// 10ms       │ Processing...           ✓ "already_known"
///            │                         └──> Returns ❌ WRONG!
/// 50ms       ✓ Receipt {status: 0x1}
///            └──> Discarded (too late)
/// 
///
/// # After Fix (Sequential Execution - Success Case):
/// 
/// Time       Transport A               Transport B
/// ─────────────────────────────────────────────────────────
/// 0ms        🚀 START
///            │
/// 10ms       │ Processing...           (not called yet)
///            │
/// 50ms       ✓ Receipt {status: 0x1}  (not called - A succeeded!)
///            └──> Returns ✅ CORRECT!
/// 
///
/// # After Fix (Sequential Execution - Fallback Case):
/// 
/// Time       Transport A               Transport B
/// ─────────────────────────────────────────────────────────
/// 0ms        🚀 START
///            │
/// 10ms       │ Processing...           (waiting...)
///            │
/// 50ms       ❌ Connection timeout
///            │
/// 51ms       (A failed, trying B...)  🚀 START
///                                      │
/// 61ms                                 │ Processing...
///                                      │
/// 101ms                                ✓ Receipt {status: 0x1}
///                                      └──> Returns ✅ CORRECT!
```

## PR Checklist

- [x] Added Tests
  - `test_non_deterministic_method_uses_sequential_fallback` - Verifies `eth_sendRawTransactionSync` uses sequential execution and returns correct receipt
  - `test_deterministic_method_uses_parallel_execution` - Verifies `eth_sendRawTransaction` continues using parallel execution for performance
- [x] Added Documentation
  - Comprehensive inline comments explaining the logic
  - Function documentation for new methods
- [ ] Breaking changes

### CODE REVIEW

File: crates/transport/src/layers/fallback.rs [hunk 1]
```diff
@@ -79,14 +146,31 @@ where
...
-    /// while keeping them available.
+    /// while ensuring correctness for methods that return different results in parallel.
     async fn make_request(&self, req: RequestPacket) -> Result<ResponsePacket, TransportError> {
+        // Check if this method returns non-deterministic results and needs sequential execution
+        let method = match &req {
+            RequestPacket::Single(r) => r.method(),
+            RequestPacket::Batch(reqs) => reqs.first().map_or("", |first| first.method()),
+        };
+
+        if requires_sequential_execution(method) {
```
Comment (mattsse) [inline crates/transport/src/layers/fallback.rs]: I think we should change this to `.any()` because even if there's a single sequential fn in a batch we should perform this sequentially

File: crates/transport/src/layers/fallback.rs [hunk 2]
```diff
@@ -68,6 +68,73 @@ impl<S: Clone> FallbackService<S> {
...
+    matches!(
+        method,
+        // EIP-7966: eth_sendRawTransactionSync - waits for receipt
+        // Parallel issue: returns receipt from first node, "already known" from others
+        "eth_sendRawTransactionSync" |
+        // eth_sendTransactionSync - same as above but for unsigned transactions
+        // Parallel issue: returns receipt from first node, "already known" from others
+        "eth_sendTransactionSync"
+    )
+}
```
Comment (mattsse) [inline crates/transport/src/layers/fallback.rs]: can we make this a hashset in the fallbacklayer itself, with these values as the default, then a user can install addiitonal ones on demand

File: crates/transport/src/layers/fallback.rs [hunk 3]
```diff
@@ -144,6 +228,58 @@ where
...
     }
+
+    /// Make a sequential request for methods with non-deterministic results.
+    ///
+    /// This method tries each transport one at a time, in order of their score.
+    /// It returns the first successful response, or an error if all transports fail.
+    ///
+    /// This approach ensures methods like `eth_sendRawTransactionSync` return the correct
+    /// receipt instead of "already known" errors from parallel execution.
+    async fn make_request_sequential(
```
Comment (mattsse) [inline crates/transport/src/layers/fallback.rs:213]: this makes sense

File: crates/transport/src/layers/fallback.rs (hunk 1 above)
Comment (Syzygy106) [reply crates/transport/src/layers/fallback.rs]: > I think we should change this to `.any()` because even if there's a single sequential fn in a batch we should perform this sequentially

Yep, that's make sense

File: crates/transport/src/layers/fallback.rs (hunk 2 above)
Comment (Syzygy106) [reply crates/transport/src/layers/fallback.rs]: > can we make this a hashset in the fallbacklayer itself, with these values as the default, then a user can install addiitonal ones on demand

ok, let me think about it
