### PR TITLE
fix: use `BlockId` superset over `BlockNumberOrTag` where applicable 

### LINKED ISSUE #1134: [Bug] Evaluate correctness of `BlockNumberOrTag` versus `BlockId` usage in RPC methods
### Component

rpc

### What version of Alloy are you on?

_No response_

### Operating System

macOS (Intel)

### Describe the bug

According to the execution API documentation: https://ethereum.github.io/execution-apis/api-documentation/ it appears that some of the RPC methods support `BlockId` (the superset incl. block hashes) rather than `BlockNumberOrTag` (tag + block numbers).

One of them is https://github.com/alloy-rs/alloy/blob/c3ccf7e2c5f9720fa6c193a9ea918aabf88aa6a2/crates/provider/src/provider/trait.rs#L323-L329 as flagged in this PR: https://github.com/foundry-rs/foundry/pull/8623

Goal of this ticket would be to go through the RPC methods and evaluate + fix where we can use the `BlockId` superset over the `BlockNumberOrTag`.

### PR DESCRIPTION
**Pull request by zerosnacks**
## Motivation

Closes #1134 

## Solution

- Aligns use with Reth implementation, using `BlockId` where implemented
  - See: [trace.rs](https://github.com/paradigmxyz/reth/blob/e907f0eab0d90f286f2197ee8935f10817ff1edf/crates/rpc/rpc/src/trace.rs)
  - See: [debug.rs](https://github.com/paradigmxyz/reth/blob/e907f0eab0d90f286f2197ee8935f10817ff1edf/crates/rpc/rpc/src/debug.rs)
- Fixes `get_block_receipts` as raised in https://github.com/foundry-rs/foundry/pull/8623
- Align parameter naming, prefer ambigious `block` for consistency
- Adds a new `--all-features` CI flag to make sure all features are actually tested, `trace` / `debug` (and presumably other) tests were not actually ran in the CI. Created https://github.com/alloy-rs/alloy/issues/1136 to investigate failing `subscribe_block_ws` and `subscribe_ws_boxed` tests on Windows now requiring skipping.

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/provider/src/provider/trait.rs [hunk 1]
```diff
@@ -1107,7 +1107,7 @@ mod tests {
         }
     }
 
-    #[cfg(feature = "ws")]
+    #[cfg(all(feature = "ws", not(windows)))]
```
Comment (zerosnacks) [inline crates/provider/src/provider/trait.rs:1110]: Note ticket: https://github.com/alloy-rs/alloy/issues/1136

File: .github/workflows/ci.yml [hunk 2]
```diff
@@ -30,6 +30,8 @@ jobs:
           - "--no-default-features"
           # Default features
           - ""
+          # All features
+          - "--all-features"
```
Comment (zerosnacks) [inline .github/workflows/ci.yml:34]: `trace`, `debug` including others were actually not being tested by the CI

I think opting for an `--all-features` CI job makes sense here as a general solution, solving issues that may arise on a case-by-case basis

**Review by mattsse — APPROVED** [review]
