### PR TITLE
fix: support Eip7594 blob format for tx build

### LINKED ISSUE #3372: [Feature] Support Eip7594 blob format for tx build
### Component

rpc + consensus

### Describe the feature you would like

While `TransactionRequest` now supports both 4844 and 7594 sidecars since #3321
https://github.com/alloy-rs/alloy/blob/9a33f527d517e3784a288343f682e04ad3eda46d/crates/rpc-types-eth/src/transaction/request.rs#L136

Building tx request with 7594 blob format doesn't work for several reasons:
- Unconditional conversion to 4844 format, 7594 format blob is simply ignored.
https://github.com/alloy-rs/alloy/blob/9a33f527d517e3784a288343f682e04ad3eda46d/crates/rpc-types-eth/src/transaction/request.rs#L585-L590
- `TxEip4844Variant`'s generic default is 4844 format
https://github.com/alloy-rs/alloy/blob/9a33f527d517e3784a288343f682e04ad3eda46d/crates/consensus/src/transaction/eip4844.rs#L32
- And likewise for typed tx
https://github.com/alloy-rs/alloy/blob/9a33f527d517e3784a288343f682e04ad3eda46d/crates/consensus/src/transaction/typed.rs#L17

The fix seems quite straightforward -- change default generic types  to use `BlobTransactionSidecarVariant ` + fix build 4844 tx method -- but breaking.

Would it be acceptable do to it now ? If so i'd happy to make a PR 👍

This would also close https://github.com/alloy-rs/alloy/issues/2455, and unlock https://github.com/foundry-rs/foundry/issues/12449 and https://github.com/foundry-rs/foundry/issues/12222. Kinda related as well: https://github.com/alloy-rs/alloy/issues/3065

### Additional context

```rust 
// eip-7594 failure repro (based on existing test build_consensus_tx_works)
let sidecar = BlobTransactionSidecarEip7594::new(vec![Blob::repeat_byte(0xFA)], Vec::new(), Vec::new());
let eip4844_request = TransactionRequest {
    to: Some(TxKind::Call(Address::repeat_byte(0xDE))),
    max_fee_per_gas: Some(1234),
    max_priority_fee_per_gas: Some(678),
    nonce: Some(57),
    gas: Some(123456),
    max_fee_per_blob_gas: Some(13579),
    blob_versioned_hashes: Some(vec![B256::repeat_byte(0xAB)]),
    sidecar: Some(sidecar.into()),
    ..Default::default()
};

// this panics because EIP-7594 sidecar is ignored
eip4844_request.build_consensus_tx().unwrap();
```

### PR DESCRIPTION
**Pull request by mablr**
## Motivation

Close #3372 

## Solution

- Change TxEip4844Variant and TxEip4844WithSidecar defaults from BlobTransactionSidecar to BlobTransactionSidecarVariant
- Fix build_4844_with_sidecar to build with EIP-4844 and EIP-7594 sidecars
- Update tests to use blob format variant enum

## PR Checklist

- [x] Added Tests
- [ ] Added Documentation
- [x] Breaking changes

### CODE REVIEW

File: crates/consensus/src/transaction/eip4844.rs [hunk 1]
```diff
@@ -29,7 +29,7 @@ use alloy_eips::eip7594::{BlobTransactionSidecarEip7594, BlobTransactionSidecarV
 #[cfg_attr(feature = "serde", serde(untagged))]
 #[cfg_attr(feature = "borsh", derive(borsh::BorshSerialize, borsh::BorshDeserialize))]
 #[doc(alias = "Eip4844TransactionVariant")]
-pub enum TxEip4844Variant<T = BlobTransactionSidecar> {
+pub enum TxEip4844Variant<T = BlobTransactionSidecarVariant> {
```
Comment (mattsse) [inline crates/consensus/src/transaction/eip4844.rs:32]: I think we can get away with this breaking change

Comment (prestwich) [reply crates/consensus/src/transaction/eip4844.rs:32]: this seems like a positive change to me
