### PR TITLE
fix(`rpc-types-eth`): receipt deser

### LINKED ISSUE #1493: [Bug] Can't deserialize old transaction receipts
### Component

network, json-rpc, serde

### What version of Alloy are you on?

alloy v0.4.2

### Operating System

Linux

### Describe the bug

We get the following serde error `missing field 'status'` when we try to get old transaction receipts e.g. [0xea1093d492a1dcb1bef708f771a99a96ff05dcab81ca76c31940300177fcf49f](https://etherscan.io/tx/0xea1093d492a1dcb1bef708f771a99a96ff05dcab81ca76c31940300177fcf49f). 

Step to reproduce :

```rust
let provider = ProviderBuilder::new().on_http("https://rpc.ankr.com/eth".parse()?);

let receipt = provider
    .get_transaction_receipt(b256!(
        "ea1093d492a1dcb1bef708f771a99a96ff05dcab81ca76c31940300177fcf49f"
    ))
    .await?;

println!("{receipt:?}");
```

### PR DESCRIPTION
**Pull request by yash-atreya**
## Motivation

Closes #1493 

## Solution

`state_root` in `TransactionReceipt` would conflict with `Eip658::PostState(root)` in `Receipt` as both have serde aliases set as `root`. Remove `state_root`. 

## PR Checklist

- [x] Added Tests
- [ ] Added Documentation
- [x] Breaking changes

### CODE REVIEW

File: crates/rpc-types-eth/src/transaction/receipt.rs [hunk 1]
```diff
@@ -67,11 +67,6 @@ pub struct TransactionReceipt<T = ReceiptEnvelope<Log>> {
     pub to: Option<Address>,
     /// Contract address created, or None if not a deployment.
     pub contract_address: Option<Address>,
-    /// The post-transaction stateroot (pre Byzantium)
-    ///
-    /// EIP98 makes this optional field, if it's missing then skip serializing it
-    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
-    pub state_root: Option<B256>,
```
Comment (mattsse) [inline crates/rpc-types-eth/src/transaction/receipt.rs:74]: yep we def need to remove this here because this is handled by the receipt
image

**Review by mattsse — APPROVED** [review]

**Comment by yash-atreya** [comment]
CI will get fixed when we bump alloy in anvil with this change. 
Currently anvil sets the `state_root` in the `TransactionReceipt`
