### PR TITLE
Fix: Support pre-658 status codes

### LINKED ISSUE #630: [Bug] Invalid encoding for pre-eip658 tx receipts
### Component

consensus, eips, genesis

### What version of Alloy are you on?

_No response_

### Operating System

None

### Describe the bug

In `alloy_consensus`, the `Receipt` struct contains the status parameter as a boolean. This is a problem when encoding pre-eip658 (added with Byzantium) receipts, as this parameter was introduced with this hardfork. In `alloy-rpc-types` the `TransactionReceipt` implements this correctly, wrapping the status as an `Option<>`.

### PR DESCRIPTION
**Pull request by prestwich**
Closes #630 

## Motivation

Support receipts from 2017 and earlier

## Solution

- Add an enum that covers the pre- and post-Eip658 values
- impl serde and rlp for that enum
- change receipt to manual serialize impl to allow for naming `root` or `status`
- add docs warning of incorrect status behavior for old receipts
- 

Open question
- when serializing, should the unused field be set to `null` by serializing a `None`?

## PR Checklist

- [ ] Added Tests
- [x] Added Documentation
- [x] Breaking changes

### CODE REVIEW

File: crates/consensus/src/receipt/receipts.rs [hunk 1]
```diff
@@ -1,31 +1,55 @@
...
 #[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
 #[doc(alias = "TransactionReceipt", alias = "TxReceipt")]
 pub struct Receipt<T = Log> {
     /// If transaction is executed successfully.
     ///
     /// This is the `statusCode`
-    #[cfg_attr(feature = "serde", serde(with = "alloy_serde::quantity_bool"))]
-    pub status: bool,
+    #[cfg_attr(feature = "serde", serde(alias = "name"))]
+    pub status: Eip658Value,
```
Comment (mattsse) [inline crates/consensus/src/receipt/receipts.rs:20]: this is a clever workaround

**Review by mattsse — APPROVED** [review]
eips 👍

File: crates/consensus/src/receipt/receipts.rs (hunk 1 above)
Comment (prestwich) [reply crates/consensus/src/receipt/receipts.rs:20]: oh i did the alias wrong lol sec
