### PR TITLE
fix(`pubsub`): retry connecting to backend

### LINKED ISSUE #2252: [Bug] No custom policy and no retry is done for disconnected web socket
### Component

provider, pubsub

### What version of Alloy are you on?

```
├── alloy v0.11.1 │   ├── alloy-consensus v0.11.1 │   │   ├── alloy-eips v0.11.1 │   │   │   ├── alloy-eip2124 v0.1.0 │   │   │   │   ├── alloy-primitives v0.8.25 │   │   │   │   │   ├── alloy-rlp v0.3.11 │   │   │   │   │   │   ├── alloy-rlp-derive v0.3.11 (proc-macro) │   │   │   │   │   │   ├── alloy-rlp v0.3.11 (*) │   │   │   │   ├── alloy-rlp v0.3.11 (*) │   │   │   ├── alloy-eip2930 v0.1.0 │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   │   ├── alloy-rlp v0.3.11 (*) │   │   │   ├── alloy-eip7702 v0.5.1 │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   │   ├── alloy-rlp v0.3.11 (*) │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   ├── alloy-rlp v0.3.11 (*) │   │   │   ├── alloy-serde v0.11.1 │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   ├── alloy-primitives v0.8.25 (*) │   │   ├── alloy-rlp v0.3.11 (*) │   │   ├── alloy-serde v0.11.1 (*) │   │   ├── alloy-trie v0.7.9 │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   ├── alloy-rlp v0.3.11 (*) │   ├── alloy-contract v0.11.1 │   │   ├── alloy-dyn-abi v0.8.25 │   │   │   ├── alloy-json-abi v0.8.25 │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   │   ├── alloy-sol-type-parser v0.8.25 │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   ├── alloy-sol-type-parser v0.8.25 (*) │   │   │   ├── alloy-sol-types v0.8.25 │   │   │   │   ├── alloy-json-abi v0.8.25 (*) │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   │   ├── alloy-sol-macro v0.8.25 (proc-macro) │   │   │   │   │   ├── alloy-sol-macro-expander v0.8.25 │   │   │   │   │   │   ├── alloy-json-abi v0.8.25 │   │   │   │   │   │   │   ├── alloy-primitives v0.8.25 │   │   │   │   │   │   │   ├── alloy-sol-type-parser v0.8.25 │   │   │   │   │   │   ├── alloy-sol-macro-input v0.8.25 │   │   │   │   │   │   │   ├── alloy-json-abi v0.8.25 (*) │   │   │   │   │   ├── alloy-sol-macro-input v0.8.25 (*) │   │   ├── alloy-json-abi v0.8.25 (*) │   │   ├── alloy-network v0.11.1 │   │   │   ├── alloy-consensus v0.11.1 (*) │   │   │   ├── alloy-consensus-any v0.11.1 │   │   │   │   ├── alloy-consensus v0.11.1 (*) │   │   │   │   ├── alloy-eips v0.11.1 (*) │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   │   ├── alloy-rlp v0.3.11 (*) │   │   │   │   ├── alloy-serde v0.11.1 (*) │   │   │   ├── alloy-eips v0.11.1 (*) │   │   │   ├── alloy-json-rpc v0.11.1 │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   │   ├── alloy-sol-types v0.8.25 (*) │   │   │   ├── alloy-network-primitives v0.11.1 │   │   │   │   ├── alloy-consensus v0.11.1 (*) │   │   │   │   ├── alloy-eips v0.11.1 (*) │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   │   ├── alloy-serde v0.11.1 (*) │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   ├── alloy-rpc-types-any v0.11.1 │   │   │   │   ├── alloy-consensus-any v0.11.1 (*) │   │   │   │   ├── alloy-rpc-types-eth v0.11.1 │   │   │   │   │   ├── alloy-consensus v0.11.1 (*) │   │   │   │   │   ├── alloy-consensus-any v0.11.1 (*) │   │   │   │   │   ├── alloy-eips v0.11.1 (*) │   │   │   │   │   ├── alloy-network-primitives v0.11.1 (*) │   │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   │   │   ├── alloy-rlp v0.3.11 (*) │   │   │   │   │   ├── alloy-serde v0.11.1 (*) │   │   │   │   │   ├── alloy-sol-types v0.8.25 (*) │   │   │   │   └── alloy-serde v0.11.1 (*) │   │   │   ├── alloy-rpc-types-eth v0.11.1 (*) │   │   │   ├── alloy-serde v0.11.1 (*) │   │   │   ├── alloy-signer v0.11.1 │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   ├── alloy-sol-types v0.8.25 (*) │   │   ├── alloy-network-primitives v0.11.1 (*) │   │   ├── alloy-primitives v0.8.25 (*) │   │   ├── alloy-provider v0.11.1 │   │   │   ├── alloy-chains v0.1.68 │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   ├── alloy-consensus v0.11.1 (*) │   │   │   ├── alloy-eips v0.11.1 (*) │   │   │   ├── alloy-json-rpc v0.11.1 (*) │   │   │   ├── alloy-network v0.11.1 (*) │   │   │   ├── alloy-network-primitives v0.11.1 (*) │   │   │   ├── alloy-node-bindings v0.11.1 │   │   │   │   ├── alloy-genesis v0.11.1 │   │   │   │   │   ├── alloy-eips v0.11.1 (*) │   │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   │   │   ├── alloy-serde v0.11.1 (*) │   │   │   │   │   ├── alloy-trie v0.7.9 (*) │   │   │   │   ├── alloy-network v0.11.1 (*) │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   │   ├── alloy-signer v0.11.1 (*) │   │   │   │   ├── alloy-signer-local v0.11.1 │   │   │   │   │   ├── alloy-consensus v0.11.1 (*) │   │   │   │   │   ├── alloy-network v0.11.1 (*) │   │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   │   │   ├── alloy-signer v0.11.1 (*) │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   ├── alloy-pubsub v0.11.1 │   │   │   │   ├── alloy-json-rpc v0.11.1 (*) │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   │   ├── alloy-transport v0.11.1 │   │   │   │   │   ├── alloy-json-rpc v0.11.1 (*) │   │   │   ├── alloy-rpc-client v0.11.1 │   │   │   │   ├── alloy-json-rpc v0.11.1 (*) │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   │   ├── alloy-pubsub v0.11.1 (*) │   │   │   │   ├── alloy-transport v0.11.1 (*) │   │   │   │   ├── alloy-transport-http v0.11.1 │   │   │   │   │   ├── alloy-json-rpc v0.11.1 (*) │   │   │   │   │   ├── alloy-transport v0.11.1 (*) │   │   │   │   ├── alloy-transport-ipc v0.11.1 │   │   │   │   │   ├── alloy-json-rpc v0.11.1 (*) │   │   │   │   │   ├── alloy-pubsub v0.11.1 (*) │   │   │   │   │   ├── alloy-transport v0.11.1 (*) │   │   │   │   ├── alloy-transport-ws v0.11.1 │   │   │   │   │   ├── alloy-pubsub v0.11.1 (*) │   │   │   │   │   ├── alloy-transport v0.11.1 (*) │   │   │   ├── alloy-rpc-types-anvil v0.11.1 │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   │   ├── alloy-rpc-types-eth v0.11.1 (*) │   │   │   │   ├── alloy-serde v0.11.1 (*) │   │   │   ├── alloy-rpc-types-debug v0.11.1 │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   ├── alloy-rpc-types-eth v0.11.1 (*) │   │   │   ├── alloy-rpc-types-trace v0.11.1 │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   │   ├── alloy-rpc-types-eth v0.11.1 (*) │   │   │   │   ├── alloy-serde v0.11.1 (*) │   │   │   ├── alloy-rpc-types-txpool v0.11.1 │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   │   ├── alloy-rpc-types-eth v0.11.1 (*) │   │   │   │   ├── alloy-serde v0.11.1 (*) │   │   │   ├── alloy-sol-types v0.8.25 (*) │   │   │   ├── alloy-transport v0.11.1 (*) │   │   │   ├── alloy-transport-http v0.11.1 (*) │   │   │   ├── alloy-transport-ipc v0.11.1 (*) │   │   │   ├── alloy-transport-ws v0.11.1 (*) │   │   ├── alloy-pubsub v0.11.1 (*) │   │   ├── alloy-rpc-types-eth v0.11.1 (*) │   │   ├── alloy-sol-types v0.8.25 (*) │   │   ├── alloy-transport v0.11.1 (*) │   ├── alloy-core v0.8.25 │   │   ├── alloy-dyn-abi v0.8.25 (*) │   │   ├── alloy-json-abi v0.8.25 (*) │   │   ├── alloy-primitives v0.8.25 (*) │   │   ├── alloy-rlp v0.3.11 (*) │   │   └── alloy-sol-types v0.8.25 (*) │   ├── alloy-eips v0.11.1 (*) │   ├── alloy-network v0.11.1 (*) │   ├── alloy-node-bindings v0.11.1 (*) │   ├── alloy-provider v0.11.1 (*) │   ├── alloy-pubsub v0.11.1 (*) │   ├── alloy-rpc-client v0.11.1 (*) │   ├── alloy-rpc-types v0.11.1 │   │   ├── alloy-primitives v0.8.25 (*) │   │   ├── alloy-rpc-types-anvil v0.11.1 (*) │   │   ├── alloy-rpc-types-beacon v0.11.1 │   │   │   ├── alloy-eips v0.11.1 (*) │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   ├── alloy-rpc-types-engine v0.11.1 │   │   │   │   ├── alloy-consensus v0.11.1 (*) │   │   │   │   ├── alloy-eips v0.11.1 (*) │   │   │   │   ├── alloy-primitives v0.8.25 (*) │   │   │   │   ├── alloy-rlp v0.3.11 (*) │   │   │   │   ├── alloy-serde v0.11.1 (*) │   │   ├── alloy-rpc-types-eth v0.11.1 (*) │   │   ├── alloy-rpc-types-trace v0.11.1 (*) │   │   ├── alloy-rpc-types-txpool v0.11.1 (*) │   │   ├── alloy-serde v0.11.1 (*) │   ├── alloy-serde v0.11.1 (*) │   ├── alloy-signer v0.11.1 (*) │   ├── alloy-signer-local v0.11.1 (*) │   ├── alloy-transport v0.11.1 (*) │   ├── alloy-transport-http v0.11.1 (*) │   ├── alloy-transport-ipc v0.11.1 (*) │   └── alloy-transport-ws v0.11.1 (*) ├── alloy-json-rpc v0.11.1 (*) ├── alloy-rlp v0.3.11 (*) │   │   │   ├── alloy-primitives v0.7.7
```

### Operating System

Linux

### Describe the bug

Retry mechanism doesn't work for web socket disconnection.

I did a provider with custom retry policy:
```rust
#[derive(Debug, Copy, Clone)]
pub struct CustomRetryPolicy;

impl Default for CustomRetryPolicy {
    fn default() -> Self {
        tracing::debug!("====> ExtendedRetryPolicy default");
        CustomRetryPolicy
    }
}
impl RetryPolicy for CustomRetryPolicy {
    fn should_retry(&self, error: &TransportError) -> bool {
        tracing::debug!("====> should_retry: {:?}", error);
        true
    }

    fn backoff_hint(&self, error: &TransportError) -> Option<Duration> {
        tracing::debug!("====> backoff_hint: {:?}", error);
        RateLimitRetryPolicy::default().backoff_hint(error)
    }
}
```
the provider:
```rust
        let retry_layer = RetryBackoffLayer::new_with_policy(
            100, 100, 100,
            CustomRetryPolicy,
        );

        let ws = WsConnect::new(geth_ws_url.to_string());

        let client = ClientBuilder::default()
            .layer(retry_layer)
            .pubsub(ws)
            .await
            .unwrap();

        let provider_ws = ProviderBuilder::new().on_client(client);
```
When I stop a container with geth I receive errors:
```
2025-03-28T10:32:52.573810Z ERROR alloy_transport_ws::native: WS connection error err=WebSocket protocol error: Connection reset without closing handshake
2025-03-28T10:32:52.573952Z  INFO alloy_pubsub::service: Reconnecting pubsub service backend.
2025-03-28T10:32:52.574373Z ERROR alloy_pubsub::service: pubsub service reconnection error err=WebSocket protocol error: Handshake not finished
```
The is no log indicating `should_retry` usage, and reconnection is not done.
What's more, later when I try to use the `provider_ws` I receive: `backend connection task has stopped`

### PR DESCRIPTION
**Pull request by yash-atreya**
## Motivation

Closes #2252 

## Solution

- retry mechanism in `PubsubService`
- Retries at least 10 times before exiting
- Interval between retires is 3 seconds

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/pubsub/src/service.rs [hunk 1]
```diff
@@ -205,16 +236,14 @@ impl<T: PubSubConnect> PubSubService<T> {
...
-                            error!("Reconnect failed, shutting down: {e}");
+                        } else if let Err(e) = self.reconnect_with_retries().await {
                             break Err(e)
                         }
                     }
 
                     _ = &mut self.handle.error => {
                         error!("Pubsub service backend error.");
-                        if let Err(e) = self.reconnect().await {
-                            error!("Reconnect failed, shutting down: {e}");
```
Comment (mattsse) [inline crates/pubsub/src/service.rs:217]: I think we still want this error message

**Review by mattsse — APPROVED** [review]
makes sense, 

this is better than terminating the task 

smol nit
