### PR TITLE
fix(pubsub): handle subscription response on reconnects (#105)

### LINKED ISSUE #105: [Bug] Pubsub backend reconnect doesn't work
### Component

pubsub

### What version of Alloy are you on?

v0.1.0 (commit 50e38e845afb27fc311a74d2260dd087f8e972f3)

### Operating System

Linux

### Describe the bug

I'm using pubsub to subscribe to `neHeads` and `logs` via my Alchemy provider, and a get this error a few times a day:

```
ERROR WS connection error while receiving a response err=WebSocket protocol error: Connection reset without closing handshake
```

immediately followed by these logs:

```
 INFO Reconnecting pubsub service backend.
DEBUG Draining old backend to_handle
DEBUG Reissuing pending requests count=0
DEBUG Re-starting active subscriptions count=2
```

And that's it, I don't receive notifications anymore after that.

After adding more traces I noticed that new subscriptions are sent to the server, but the responses are not handled, because the reconnect logic doesn't add back in-flight request, and it's needed:

https://github.com/alloy-rs/alloy/blob/4db40b051a1f2443b9c18fa0cf62d0ac24d07012/crates/pubsub/src/service.rs#L165-L176

Another issue: Looking at `PubSubService::reconnect()`, I noticed that  [all server ids are dropped](https://github.com/alloy-rs/alloy/blob/4db40b051a1f2443b9c18fa0cf62d0ac24d07012/crates/pubsub/src/service.rs#L93), leading to close the connection between the backend and the frontend.

### PR DESCRIPTION
**Pull request by leruaa**
## Motivation

Closes #105 

## Solution

* Add a in-flight request for each subscription requests to be dispached on reconnect
* Don't drop server ids to be able to update them when handling subscription responses

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/pubsub/src/service.rs [hunk 1]
```diff
@@ -89,15 +91,13 @@ where
...
-        self.subs.drop_server_ids();
         // Dispatch all subscription requests
         self.subs
             .iter()
-            .map(|(_, sub)| sub.request().serialized().to_owned())
+            .map(|(_, sub)| sub.request().to_owned())
             .collect::<Vec<_>>()
             .into_iter()
-            .try_for_each(|brv| self.dispatch_request(brv))?;
+            .try_for_each(|req| self.dispatch_subscription(req))?;
```
Comment (DaniPopes) [inline crates/pubsub/src/service.rs:100]: What's the reason for collecting here? cc @prestwich

Comment (leruaa) [reply crates/pubsub/src/service.rs:100]: I think that without collecting closure requires unique access to `*self` but it is already borrowed

Comment (prestwich) [reply crates/pubsub/src/service.rs:100]: yes, self is borrowed by the `Map<Iter<..>>` and collecting ends that borrow so that the `try_for_each` can get `&mut self`

File: crates/pubsub/src/managers/in_flight.rs [hunk 2]
```diff
@@ -13,26 +13,31 @@ pub(crate) struct InFlight {
     pub(crate) request: SerializedRequest,
 
     /// The channel to send the response on.
-    pub(crate) tx: oneshot::Sender<Result<Response, TransportError>>,
+    pub(crate) tx: Option<oneshot::Sender<Result<Response, TransportError>>>,
```
Comment (prestwich) [inline crates/pubsub/src/managers/in_flight.rs:16]: instead of changing the type here, you can just make a broken sender with `let (tx, _) = oneshot::channel();`

Comment (prestwich) [reply crates/pubsub/src/managers/in_flight.rs:16]: or use `Inflight::new` and then drop the receiver/waiter

File: crates/pubsub/src/service.rs (hunk 1 above)
Comment (prestwich) [reply crates/pubsub/src/service.rs:100]: could probably be simplified into a single `try_for_each`

File: crates/pubsub/src/service.rs [hunk 3]
```diff
@@ -89,15 +91,13 @@ where
         // Re-subscribe to all active subscriptions
         tracing::debug!(count = self.subs.len(), "Re-starting active subscriptions");
 
-        // Drop all server IDs. We'll re-insert them as we get responses.
-        self.subs.drop_server_ids();
```
Comment (prestwich) [inline crates/pubsub/src/service.rs:93]: removing this causes memory leak on each reconnect

**Review by prestwich — COMMENTED** [review]
can you explain the reasoning behind this fix? i.e. why do we believe it addresses the issue?

It looks like the main difference is the Inflight added [here](https://github.com/alloy-rs/alloy/pull/107/files#diff-46c2aec33612b9f33b878dfd28165670efb45a552e06e4bf2fac8f55e51b7a11R111)

File: crates/pubsub/src/service.rs (hunk 3 above)
Comment (prestwich) [reply crates/pubsub/src/service.rs:93]: server IDs are dropped as they are no longer valid, btw. the server will issue new IDs on reconnect and all old IDs are now dead

File: crates/pubsub/src/service.rs (hunk 1 above)
Comment (DaniPopes) [reply crates/pubsub/src/service.rs:100]: If `dispatch_subscription` is inlined it can be because the borrows get split to the individual fields

**Comment by leruaa** [comment]
@prestwich Indeed. It seems that on reconnects, if there are no in-flight request, new subscription responses are not handled, see below:
https://github.com/alloy-rs/alloy/blob/4db40b051a1f2443b9c18fa0cf62d0ac24d07012/crates/pubsub/src/service.rs#L167

File: crates/pubsub/src/service.rs (hunk 3 above)
Comment (leruaa) [reply crates/pubsub/src/service.rs:93]: I remember that new subscription messages were not sent to the frontend if server ids weren't dropped... I'll do more tests

Comment (leruaa) [reply crates/pubsub/src/service.rs:93]: Ok, so here's what's happening:

On reconnect server ID are dropped (i.e. `local_to_server` is cleared). When the new subscription response is handled (in [handle_sub_response](https://github.com/alloy-rs/alloy/blob/d68e1103bda0a0b95e1928c56091dc48e64c95de/crates/pubsub/src/service.rs#L179)), we call `upsert` to insert or update the server_id. 

But, as `local_to_server` is cleared, instead of just changing the server ID, we insert a new `ActiveSubscription`, dropping the old one *and* the associated `Sender`, leading to close the corresponding `Receiver` on the frontend side.

**Comment by leruaa** [comment]
@prestwich Yes I just did, see my comment [above ](https://github.com/alloy-rs/alloy/pull/107#discussion_r1466648031)

**Comment by prestwich** [comment]
ah simultaneous comments. seems the check in upsert `self.local_to_server.contains_left(&local_id)` should be `self.local_to_sub.contains(&local_id)` ?

**Comment by leruaa** [comment]
That make sense, I will test.

**Review by prestwich — APPROVED** [review]
lgtm
