### PR TITLE
[Fix] use Eip2718Error, add docs on different encodings

### LINKED ISSUE #283: [Feature] Provide examples for and document encoding with Encodable2718 and Decodable2718
### Component

consensus, eips, genesis, network, json-rpc

### Describe the feature you would like

ref https://github.com/alloy-rs/alloy/pull/239#discussion_r1521652211

`Encodable2718` and `Decodable2718` are how most users should implement and perform tx encoding / decoding. Examples for using this (for example to send a raw transaction) and how to implement this on a different tx type should be added.

Documentation should be added that clarifies the difference between the network and rpc formats, and why these two formats motivate the existence of the trait.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by prestwich**
closes #283 and more!

## Motivation

Turns out we weren't even using the 2718 error type.

## Solution

Change Decodable2718 to use the error type.
Add docs about network encoding vs 2718 encoding
remove erroneous references to RLP in 2718 docs

## PR Checklist

- [ ] Added Tests
- [x] Added Documentation
- [x] Breaking changes

### CODE REVIEW

File: crates/eips/src/eip2718.rs [hunk 1]
```diff
@@ -111,15 +136,26 @@ pub trait Decodable2718: Sized {
...
         }
 
         Ok(tx)
     }
 }
 
 /// Encoding trait for [EIP-2718] envelopes. These envelopes wrap a transaction
-/// or a receipt with a type flag.
+/// or a receipt with a type flag. [EIP-2718] encodings are used by the
+/// `eth_sendTransaction` RPC call, the Ethereum block header's tries, and the
```
Comment (mattsse) [inline crates/eips/src/eip2718.rs:148]:
```suggestion
/// `eth_sendRawTransaction` RPC call, the Ethereum block header's tries, and the
```

File: crates/eips/src/eip2718.rs [hunk 2]
```diff
@@ -169,9 +209,12 @@ pub trait Encodable2718: Sized + Send + Sync + 'static {
...
 
-    /// Return the network encoding. For non-legacy items, this is the RLP
-    /// encoding of the bytestring of the 2718 encoding. For legacy items it is
-    /// simply the legacy encoding.
+    /// Encode in the network format. The network format is used ONLY by the
+    /// Ethereum p2p protocol. Do not call this method unless you are building
+    /// a p2p protocol client.
+    ///
+    /// The network encoding is the RLP encoding of the eip2718-encoded
+    /// envelope.
```
Comment (mattsse) [inline crates/eips/src/eip2718.rs:217]: this cost me days of my life

**Review by mattsse — APPROVED** [review]
