### PR TITLE
fix(`provider`): custom deser for pending blocks

### LINKED ISSUE #2117: [Bug] Deserialization error on get_block for pending data on BSC
### Component

serde

### What version of Alloy are you on?

0,11,1

### Operating System

Linux

### Describe the bug

Hello, 
I'm getting a deserialize error when trying to fetch pending block data using 
`provider.get_block(BlockId::pending(), BlockTransactionsKind::Hashes)`

```
called `Result::unwrap()` on an `Err` value: DeserError { err: Error("invalid type: null, expected 32 bytes, represented as a hex string of length 64, an array of u8, or raw bytes", line: 1, column: 9266), text: "{\"baseFeePerGas\":\"0x0\",\"blobGasUsed\":\"0x40000\",\"difficulty\":\"0x2\",\"excessBlobGas\":\"0x0\",\"extraData\":\"0xd983010412846765746889676f312e32312e3133856c696e7578000060adae27f8b58317ffffb860a77ce14aeaf26b0099df5118f0751f6975fe18c91804e9affb0b468f59b997de33b98853f1d477bbf0396b9a6d674a420ba0ee2d83b8429a36b23bc0d3155c26924a37d9608a6845bf0b6292e167b70aa63a840201aa5a67f09de28bec0582fdf84c8402cb0a92a0b34a963e856bf10286829796602b508515555c2eca2a2e1305db239a33d0301a8402cb0a93a0275ca5b621bb2783f7bcdfdd5e14428dee3f2706669c6b66af463853484a4287800ebe41f4dac1f0dcef91ad0eb84115efb4b7ca72667746cdce217429766b51141502846fece71ef05843c2f0348974c7f4e06a74d56d6ced93277b6f6912afec01\",\"gasLimit\":\"0x8583b00\",\"gasUsed\":\"0xc684f8\",\"hash\":null,\"logsBloom\":\"0x15ed82ee9d020418029188d2b4202b453484128a082992086d67a27025889504c001590362c3d1aa804648359a1f080a840dd0a18caafc500e800061902727a26c489090a960386e03101918a1630124e07c3237415c0f48d10d1096b8a054394709b42a43f22a33154a03b1a5c01821ac20947700818da4305c489ce08e00cd0825e560e5202ac136980e020c288ceb60e526a51202810c6b4229c813d05a6882cc193b3b2079254b1660ca2694193901174a6ee392801190455031222872d54187f1164722551225aa800941699a14a2c035300564861c0656c22b2185e4781edd338144316c030b495ae40469c5c7193cdd04c10461e87708c02294c9703e\",\"miner\":null,\"mixHash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"nonce\":null,\"number\":\"0x2cb0a94\",\"parentBeaconBlockRoot\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"parentHash\":\"0x275ca5b621bb2783f7bcdfdd5e14428dee3f2706669c6b66af463853484a4287\",\"receiptsRoot\":\"0x3a141664e592b274981a20d43b98ae9fd7a04982fca7bb1ace74cbbf789bf932\",\"sha3Uncles\":\"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347\",\"size\":\"0xa445\",\"stateRoot\":\"0x92817c00d5c7aa90f1663bdbc7978c87d2339d8c08fdc1d228068a81e2034f89\",\"timestamp\":\"0x67b8cd0c\",\"totalDifficulty\":\"0x58d40eb\",\"transactions\":[\"0x92b24a5a6f9e0595a66261dadab168959f0ec7a717a648e77d64841fd1a87b29\",\"0x3a317c4dbe8988a37aa904a5004b7c43f634973875c7530d715b126720c0f5b8\",\"0xe0ff59c07d8fb69334d41a5a0ab93d2d233d3241ba6b732b735f6bfd391c5ae3\",\"0x4a3558068417f324c244c5167c51ab53822fcf5152884fb4e6f5c4041dacf342\",\"0x2fff6be1f4fd369deab3f56e9b149a13aefabe0185a94587a6d76ca7573e9a78\",\"0xe9cfe932ae906aaada4f6bc5316e90dd2db6ad882ea5ee0e8e3e265284f11ed9\",\"0x55e00967f41418878513e15a32280b0ea03206c7b990e4ffba154dc85b9d1824\",\"0x979d485ca38ecc1e4937e3f718fe0d8ae84ebc9e949272f9794c5b81f74871c9\",\"0xe4bd6f089daa08c7a33b8ff92496b9b1e1e238d8d63f96e353e38ac775240831\",\"0x2596e622434d47cafd2bc2883f60cee9e983277c8340750db3358308db18ff16\",\"0x4782bdf933b6c1cd08e44b63fa7215ede67d5a7a9af3da5372c221d1e39aeb87\",\"0x786135f1162d3a7dd10f590ef7e96865d86dc76db6029e5c3e9df362748b3bd6\",\"0xb04a69125d7b44a43151012b4f8829f4937a2ffa5c15d8345cf2caf642abf446\",\"0x95842ecbefd2a53afb067a421deb9d48aeb6e5a6b97e086ffe1e52d143a9990b\",\"0x1722f12a3ed85ff0c8daf5cda32dc9d72b92a10a76e9d28329163bde9a4c8955\",\"0xdd7a99c365f540eb110c9ce4d395a096170ca85e6c71a7636eabcd40d2f1f68a\",\"0x09dfa2cd973be0e83cfb23798fa37f603f5c842ccf2c88a1097af07e7a36aad7\",\"0x28cde38672c45ef7b0fa748e9d8f916ae324cabc4759844cd4933eac65ea39b9\",\"0x9072bd1360e0961c8d6fa5f02ae8f36938e5db597041060438cf8fc00d87c818\",\"0xfb287312c7bb18351c5aa50052100301eb2bf6cae4c03d720cc6ce4028f24be9\",\"0xc8ee8de744abdbd7acf6eb71e7d32a6d6cd39f86e4e112079466cce489e71d8b\",\"0x0e362bf5e479e3376b330730480fb37f92c925e3cb067116d97429090fdb62f9\",\"0xd076266f0c8590590410dd7e467e333b7e4bcff335079127c0fb9e063d73f556\",\"0x6bc7f75fafb5f26cacc6814655c966887c60942f34b3d7ef7a5e404d895f0fe6\",\"0xf3db2588ce58a80562ff23788cd62c40e6ca0869e9583f1b4c869842e373e19c\",\"0x3c633432adac7b2b1eda7cdadd0d8a7d4c90c8d01f66d53f3912712563fe745f\",\"0x47277bd0f42b6b273517adca6e9b063822848ee944c7a5821b78c36babc8b4d7\",\"0xbca2783b0c45da5fdd811b178e8e61acb8bba40f04ffc00089ba79623cbf4a25\",\"0x5704b57622153d82a126008c64f908ddca2ae3ef5d85cc6d0fc7c689f1d6786f\",\"0x01dc5777ed2bcc98d0cfe35afb98613120693a355f004f7202809d546d359cac\",\"0x986008bb37df53950b717b5f8c821781fc50eced780e85d390a9d9f449609c1a\",\"0x5fa3cf56068f08f7492d954a9e98aed252cfbc8bf06ccab69563ef3fa9129b30\",\"0x3b1bcb283e98f915f6501b02bc3173f8068596327f77dd9b733cf573e0e7ec9e\",\"0xaaae11cfc07d941a45811a275e4ac6bfe92b788df4f5a1ac078946da59ef5283\",\"0x3995a97cc5717ae55b29c20d50ba523f9a45ceb0ea88c0083fe2fae9ee4242b3\",\"0x1d3ae6568e5ff976394f018d62b73d6a6151c2b3d95c1fb7a429f192a29b8ef5\",\"0x2921ac00857510e235e0c467e1fd543c6098475468ae47a64c224a1c772ad551\",\"0xe70e5bd61b9d51a0344e6a614ccb64c266e82795f0b42fa1c5111eb5bfe24e2f\",\"0x4e1dee5e6241e898d564b50be203022cc998a6632bf29e5f7c6b189a27b86b92\",\"0x8ba75908623b4995f351e33a04fe07f149e052a30d17b92d1b41ccf22c7b7608\",\"0xaa83526a0cbba0c9b2415942c6a637fbab9a6d0de20a2532908b4d947c587064\",\"0x22b95128809c98c0ba264263c2688e2a8dab12ae17f3b730bd5648e46fd5efb9\",\"0xcc6f6fe8240831d47becbf55aa30222dec06bcfe928332dd1178ab2e0d5610a5\",\"0xf41dd553c364611bd5ab87423a6701b1985fd9ffc48264dae62e5dcbf1ea0479\",\"0xc1212086314f6fe71a7cab74b2a873ab1e4a329e3de778dce3ea50c767d52eed\",\"0xe7f5dd3b72dac97f553f3b6bd979e7a14b4f98cca91378ea2f0f45841644d2b9\",\"0x0f083d5eefa8e1aefbbe83fafb62b7df9e69075b4828a66572932e0c65bb45b1\",\"0xf9cdb766d63dc0b0a9efd490ff8a2555df6f5c06552bd600edd5935dae1af271\",\"0x6d338cd6914349ae983dfe671c9bfbdfd15ed3d099559e6ef2c33491dbcbc549\",\"0x7bf50c1b5808eaec500b84d8eebb1f850e474b1292131378a001c35177f5963d\",\"0x1a2a6b1a7820ef57b5c12e7056de0775c5a5d00575292531d62cb8e760b40e97\",\"0xa349007835b08cd3e4263f703396ba3d47144493ff29fde28e5935cd707a7c2e\",\"0xcce14fd77e715c715b4c067efaf5f0989df5d15b83975fce4c3e632f8df40162\",\"0xa31388211682eb977199cc5f325757250201f7dbc23b309dc5d656bd55368511\",\"0x33f3c38c9cf73340dbd7c16361e13e351b6b955c5620e6c8ac5f21c1eb0c9ec0\",\"0x89bc8fb4ce905dff57453871159085f15bb5a83d5e8cdf2983c9fa5c168bbb62\",\"0x1b2333b9070cbb829a18ef812a669bb2788892e390373e1bb71decf0a071b78f\",\"0x7d698e8f7ce9b951371a29cc5adfbc0d81bda2ff7d70e7205c40bd58c87bf193\",\"0x99454d5c5658b6d6655dd685c430cdd51f9ff599fd68b639003b8f34250e7c66\",\"0x13b57919c81fe5a5c036fae99ddfcf4e8df3d00b92cfc454e3ec80ab91e2ad50\",\"0x8d7b832b157602512d0f878ffc5336abfb02ffc9ecbf9a5d42498fe02a13ddad\",\"0x25c4b90e0957ecdeb620381fe52598f730801bdefb666af10dc2e04e437d8288\",\"0x741adf6144c3e7e4f4482402cb963b4b4a7f4eba724cde88f7a6960583b3a0a2\",\"0x8e82fb0ddc3aa333412a0f9aeefbc52c24d7275920ba3d41acea626d4c04b9c5\",\"0x6b5f82bbec3f1ba03283c3fb6cfcc82993386a4765bfb8b0114c917990ae4d46\",\"0xd0be1eea6550db8acf98b64609bd49cc27d3b429f024e1c06ad4316e8ca1139e\",\"0x077d357ca7ae9e178e6e70a22a6bad0b222998098d0d2d063bd675219437f8e4\",\"0x3a64065e4c8fb42fd251532c31580393b1029e343880a407ed64bdebf6837c2c\",\"0xef4b5f41489123bca3760f6549d0cd17f728639ec805d5c3196e670815c558cb\",\"0xcd8f6f1dc426a96de33bcc3a7107bb59531b5584dac70490a0318326cf4fe86d\",\"0x01a6c90bb385134c9a50b30b3a69a377d00d54065a9cd96215df2c9712eb2c56\",\"0xe70f5c5364fce0a8b29af8639bc3fb037c83bc0f9bc5aa85061c36a44f82522f\",\"0xf9082440c5dd533831fccf89b200f573c5310c4fc4e7801f90d59b4b78692001\",\"0xdc86b2dcfbdd0832367c1ce7a20182133e2ba39a2c8a70234b3062c651782fdd\",\"0xe1c72b3cd9c424738819b331dd56a8ff71380954a56edd0f4c002c94db1128bc\",\"0x9a460be846c4e04e074a21579647fa0015f275f95327cfcd801bd060c3ba94f7\",\"0x3ded1378f0d914e41f10176862aba832667beaa237581311aecf469db79d57cc\",\"0xd59c1fe6d686c13944a304dccb1be3b7161ef107f9f6fc97051cac69c68223f3\",\"0x9c7934d129b9369d96012061d99706fc3c7cb0cb1a5e1ac97cf4540219f7a66c\",\"0x452211703efe416c60c3b2bc1234cf6dc54276f80b6562897f6ac33902deb7d6\",\"0xf8366e9902b6c8fdcb9cb841ebc79c358c0c240a9bdbe6e59958ddcb87e7db16\",\"0xe11f95878b6e4989bccccf6b427bce6fe3f0f4aadb018f994e4d86554937f27c\",\"0x697dc185262209c116ed4ebe0c0e6398850cb1c12a30d424fd8a525a1a93b15a\",\"0x5b015dd88412a098faa012602ea34c993dbaf4ab7e65711457b9f2471901eac3\",\"0x252a2d4338652dd7700d0e5fb7f58156a59bb338860bfe92c25102077c80f426\",\"0x8e8f59137794e9bf532660c803c8cf015906c78e9608d293abd1f03d03f4457e\",\"0x80ac934070ca9d49d935fd1b59db4e7c72bb07627ed2404ee29994109a3bce0a\",\"0x5da8711c95b0ffd66a34bb075e018dd4dbdeb69eb027d4034ccd61507aa0e8ef\",\"0xccfb0b3c815e330ee54778a70e8d7f87e44f503b7eaeca5d49eb8c7ca1e94d07\",\"0x2893fee57e45d4193fb7faef56c44b4073991a290b47ec01df41a4095da732c8\",\"0xd12d948e81d0065e3b3f4da363cde94d955403b33c3b8c413d579e83b290b2f9\",\"0x7363978f57b80e43bfa1f680cbde29e395e282dcb260f83564a9479c0d6d9043\",\"0x04c2fddec950d586658f95d9bc5a119cff17c4b4674121bba119b3a9141aa8d2\",\"0x3468842a38b3bbadfb6fee7ae9d7f1905399864a04b728cae5459cf285d1ab04\",\"0xd1e53710afc9cde2aff165a5e051f872d06b7fdaa7472d69d3b4e4dc06a18314\",\"0x4b00b3a617b29e6a6ee2da22d6ccc84e4b80e764b7cde43bcb35fd5b6c54e56c\",\"0x1e3d07b3b5e03b319b19427882c978b1e1abf57773f2c38d42070e5a9698532d\",\"0x072d7abbcb09ed45e0b66da3e4e6a3d8711f8f340deb185fb23dfd54e4ea857d\",\"0x0e0886bb93300886b22eece04baaec3ad3aa21a356fc663f0906f3a224241eb2\",\"0x1881245891db70d5c70a3b47c7b1ade606372f258612c361c85210e32f7aabbc\",\"0xdbc932378933e6c8210b5a63461926b3ddc51a450b7ede2261fff9e610d351e1\",\"0xa199de162d8bbcc2968d1e8666d19900e846db6624a3ec0189ed482257950f5a\",\"0xe32c94a81472a193adcdb6fd747382efb16fa03dec170c5618db5e4e8ff14ff3\",\"0xb157437688533fa8effb32b1fa2decb068acb40cde29e02961f92f29f49a0683\"],\"transactionsRoot\":\"0x56f32aeb5d8d992f0551f4fca41cde702a676bf95fea3351ecd013e7691b90c2\",\"uncles\":[],\"withdrawals\":[],\"withdrawalsRoot\":\"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421\"}" }`
```

JSON:
```json
{
    "baseFeePerGas": "0x0",
    "blobGasUsed": "0x40000",
    "difficulty": "0x2",
    "excessBlobGas": "0x0",
    "extraData": "0xd983010412846765746889676f312e32312e3133856c696e7578000060adae27f8b58317ffffb860a77ce14aeaf26b0099df5118f0751f6975fe18c91804e9affb0b468f59b997de33b98853f1d477bbf0396b9a6d674a420ba0ee2d83b8429a36b23bc0d3155c26924a37d9608a6845bf0b6292e167b70aa63a840201aa5a67f09de28bec0582fdf84c8402cb0a92a0b34a963e856bf10286829796602b508515555c2eca2a2e1305db239a33d0301a8402cb0a93a0275ca5b621bb2783f7bcdfdd5e14428dee3f2706669c6b66af463853484a4287800ebe41f4dac1f0dcef91ad0eb84115efb4b7ca72667746cdce217429766b51141502846fece71ef05843c2f0348974c7f4e06a74d56d6ced93277b6f6912afec01",
    "gasLimit": "0x8583b00",
    "gasUsed": "0xc684f8",
    "hash": null,
    "logsBloom": "0x15ed82ee9d020418029188d2b4202b453484128a082992086d67a27025889504c001590362c3d1aa804648359a1f080a840dd0a18caafc500e800061902727a26c489090a960386e03101918a1630124e07c3237415c0f48d10d1096b8a054394709b42a43f22a33154a03b1a5c01821ac20947700818da4305c489ce08e00cd0825e560e5202ac136980e020c288ceb60e526a51202810c6b4229c813d05a6882cc193b3b2079254b1660ca2694193901174a6ee392801190455031222872d54187f1164722551225aa800941699a14a2c035300564861c0656c22b2185e4781edd338144316c030b495ae40469c5c7193cdd04c10461e87708c02294c9703e",
    "miner": null,
    "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "nonce": null,
    "number": "0x2cb0a94",
    "parentBeaconBlockRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "parentHash": "0x275ca5b621bb2783f7bcdfdd5e14428dee3f2706669c6b66af463853484a4287",
    "receiptsRoot": "0x3a141664e592b274981a20d43b98ae9fd7a04982fca7bb1ace74cbbf789bf932",
    "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
    "size": "0xa445",
    "stateRoot": "0x92817c00d5c7aa90f1663bdbc7978c87d2339d8c08fdc1d228068a81e2034f89",
    "timestamp": "0x67b8cd0c",
    "totalDifficulty": "0x58d40eb",
    "transactions": [
        "0x92b24a5a6f9e0595a66261dadab168959f0ec7a717a648e77d64841fd1a87b29",
        "0x3a317c4dbe8988a37aa904a5004b7c43f634973875c7530d715b126720c0f5b8",
        "0xe0ff59c07d8fb69334d41a5a0ab93d2d233d3241ba6b732b735f6bfd391c5ae3",
        "0x4a3558068417f324c244c5167c51ab53822fcf5152884fb4e6f5c4041dacf342",
        "0x2fff6be1f4fd369deab3f56e9b149a13aefabe0185a94587a6d76ca7573e9a78",
        "0xe9cfe932ae906aaada4f6bc5316e90dd2db6ad882ea5ee0e8e3e265284f11ed9",
        "0x55e00967f41418878513e15a32280b0ea03206c7b990e4ffba154dc85b9d1824",
        "0x979d485ca38ecc1e4937e3f718fe0d8ae84ebc9e949272f9794c5b81f74871c9",
        "0xe4bd6f089daa08c7a33b8ff92496b9b1e1e238d8d63f96e353e38ac775240831",
        "0x2596e622434d47cafd2bc2883f60cee9e983277c8340750db3358308db18ff16",
        "0x4782bdf933b6c1cd08e44b63fa7215ede67d5a7a9af3da5372c221d1e39aeb87",
        "0x786135f1162d3a7dd10f590ef7e96865d86dc76db6029e5c3e9df362748b3bd6",
        "0xb04a69125d7b44a43151012b4f8829f4937a2ffa5c15d8345cf2caf642abf446",
        "0x95842ecbefd2a53afb067a421deb9d48aeb6e5a6b97e086ffe1e52d143a9990b",
        "0x1722f12a3ed85ff0c8daf5cda32dc9d72b92a10a76e9d28329163bde9a4c8955",
        "0xdd7a99c365f540eb110c9ce4d395a096170ca85e6c71a7636eabcd40d2f1f68a",
        "0x09dfa2cd973be0e83cfb23798fa37f603f5c842ccf2c88a1097af07e7a36aad7",
        "0x28cde38672c45ef7b0fa748e9d8f916ae324cabc4759844cd4933eac65ea39b9",
        "0x9072bd1360e0961c8d6fa5f02ae8f36938e5db597041060438cf8fc00d87c818",
        "0xfb287312c7bb18351c5aa50052100301eb2bf6cae4c03d720cc6ce4028f24be9",
        "0xc8ee8de744abdbd7acf6eb71e7d32a6d6cd39f86e4e112079466cce489e71d8b",
        "0x0e362bf5e479e3376b330730480fb37f92c925e3cb067116d97429090fdb62f9",
        "0xd076266f0c8590590410dd7e467e333b7e4bcff335079127c0fb9e063d73f556",
        "0x6bc7f75fafb5f26cacc6814655c966887c60942f34b3d7ef7a5e404d895f0fe6",
        "0xf3db2588ce58a80562ff23788cd62c40e6ca0869e9583f1b4c869842e373e19c",
        "0x3c633432adac7b2b1eda7cdadd0d8a7d4c90c8d01f66d53f3912712563fe745f",
        "0x47277bd0f42b6b273517adca6e9b063822848ee944c7a5821b78c36babc8b4d7",
        "0xbca2783b0c45da5fdd811b178e8e61acb8bba40f04ffc00089ba79623cbf4a25",
        "0x5704b57622153d82a126008c64f908ddca2ae3ef5d85cc6d0fc7c689f1d6786f",
        "0x01dc5777ed2bcc98d0cfe35afb98613120693a355f004f7202809d546d359cac",
        "0x986008bb37df53950b717b5f8c821781fc50eced780e85d390a9d9f449609c1a",
        "0x5fa3cf56068f08f7492d954a9e98aed252cfbc8bf06ccab69563ef3fa9129b30",
        "0x3b1bcb283e98f915f6501b02bc3173f8068596327f77dd9b733cf573e0e7ec9e",
        "0xaaae11cfc07d941a45811a275e4ac6bfe92b788df4f5a1ac078946da59ef5283",
        "0x3995a97cc5717ae55b29c20d50ba523f9a45ceb0ea88c0083fe2fae9ee4242b3",
        "0x1d3ae6568e5ff976394f018d62b73d6a6151c2b3d95c1fb7a429f192a29b8ef5",
        "0x2921ac00857510e235e0c467e1fd543c6098475468ae47a64c224a1c772ad551",
        "0xe70e5bd61b9d51a0344e6a614ccb64c266e82795f0b42fa1c5111eb5bfe24e2f",
        "0x4e1dee5e6241e898d564b50be203022cc998a6632bf29e5f7c6b189a27b86b92",
        "0x8ba75908623b4995f351e33a04fe07f149e052a30d17b92d1b41ccf22c7b7608",
        "0xaa83526a0cbba0c9b2415942c6a637fbab9a6d0de20a2532908b4d947c587064",
        "0x22b95128809c98c0ba264263c2688e2a8dab12ae17f3b730bd5648e46fd5efb9",
        "0xcc6f6fe8240831d47becbf55aa30222dec06bcfe928332dd1178ab2e0d5610a5",
        "0xf41dd553c364611bd5ab87423a6701b1985fd9ffc48264dae62e5dcbf1ea0479",
        "0xc1212086314f6fe71a7cab74b2a873ab1e4a329e3de778dce3ea50c767d52eed",
        "0xe7f5dd3b72dac97f553f3b6bd979e7a14b4f98cca91378ea2f0f45841644d2b9",
        "0x0f083d5eefa8e1aefbbe83fafb62b7df9e69075b4828a66572932e0c65bb45b1",
        "0xf9cdb766d63dc0b0a9efd490ff8a2555df6f5c06552bd600edd5935dae1af271",
        "0x6d338cd6914349ae983dfe671c9bfbdfd15ed3d099559e6ef2c33491dbcbc549",
        "0x7bf50c1b5808eaec500b84d8eebb1f850e474b1292131378a001c35177f5963d",
        "0x1a2a6b1a7820ef57b5c12e7056de0775c5a5d00575292531d62cb8e760b40e97",
        "0xa349007835b08cd3e4263f703396ba3d47144493ff29fde28e5935cd707a7c2e",
        "0xcce14fd77e715c715b4c067efaf5f0989df5d15b83975fce4c3e632f8df40162",
        "0xa31388211682eb977199cc5f325757250201f7dbc23b309dc5d656bd55368511",
        "0x33f3c38c9cf73340dbd7c16361e13e351b6b955c5620e6c8ac5f21c1eb0c9ec0",
        "0x89bc8fb4ce905dff57453871159085f15bb5a83d5e8cdf2983c9fa5c168bbb62",
        "0x1b2333b9070cbb829a18ef812a669bb2788892e390373e1bb71decf0a071b78f",
        "0x7d698e8f7ce9b951371a29cc5adfbc0d81bda2ff7d70e7205c40bd58c87bf193",
        "0x99454d5c5658b6d6655dd685c430cdd51f9ff599fd68b639003b8f34250e7c66",
        "0x13b57919c81fe5a5c036fae99ddfcf4e8df3d00b92cfc454e3ec80ab91e2ad50",
        "0x8d7b832b157602512d0f878ffc5336abfb02ffc9ecbf9a5d42498fe02a13ddad",
        "0x25c4b90e0957ecdeb620381fe52598f730801bdefb666af10dc2e04e437d8288",
        "0x741adf6144c3e7e4f4482402cb963b4b4a7f4eba724cde88f7a6960583b3a0a2",
        "0x8e82fb0ddc3aa333412a0f9aeefbc52c24d7275920ba3d41acea626d4c04b9c5",
        "0x6b5f82bbec3f1ba03283c3fb6cfcc82993386a4765bfb8b0114c917990ae4d46",
        "0xd0be1eea6550db8acf98b64609bd49cc27d3b429f024e1c06ad4316e8ca1139e",
        "0x077d357ca7ae9e178e6e70a22a6bad0b222998098d0d2d063bd675219437f8e4",
        "0x3a64065e4c8fb42fd251532c31580393b1029e343880a407ed64bdebf6837c2c",
        "0xef4b5f41489123bca3760f6549d0cd17f728639ec805d5c3196e670815c558cb",
        "0xcd8f6f1dc426a96de33bcc3a7107bb59531b5584dac70490a0318326cf4fe86d",
        "0x01a6c90bb385134c9a50b30b3a69a377d00d54065a9cd96215df2c9712eb2c56",
        "0xe70f5c5364fce0a8b29af8639bc3fb037c83bc0f9bc5aa85061c36a44f82522f",
        "0xf9082440c5dd533831fccf89b200f573c5310c4fc4e7801f90d59b4b78692001",
        "0xdc86b2dcfbdd0832367c1ce7a20182133e2ba39a2c8a70234b3062c651782fdd",
        "0xe1c72b3cd9c424738819b331dd56a8ff71380954a56edd0f4c002c94db1128bc",
        "0x9a460be846c4e04e074a21579647fa0015f275f95327cfcd801bd060c3ba94f7",
        "0x3ded1378f0d914e41f10176862aba832667beaa237581311aecf469db79d57cc",
        "0xd59c1fe6d686c13944a304dccb1be3b7161ef107f9f6fc97051cac69c68223f3",
        "0x9c7934d129b9369d96012061d99706fc3c7cb0cb1a5e1ac97cf4540219f7a66c",
        "0x452211703efe416c60c3b2bc1234cf6dc54276f80b6562897f6ac33902deb7d6",
        "0xf8366e9902b6c8fdcb9cb841ebc79c358c0c240a9bdbe6e59958ddcb87e7db16",
        "0xe11f95878b6e4989bccccf6b427bce6fe3f0f4aadb018f994e4d86554937f27c",
        "0x697dc185262209c116ed4ebe0c0e6398850cb1c12a30d424fd8a525a1a93b15a",
        "0x5b015dd88412a098faa012602ea34c993dbaf4ab7e65711457b9f2471901eac3",
        "0x252a2d4338652dd7700d0e5fb7f58156a59bb338860bfe92c25102077c80f426",
        "0x8e8f59137794e9bf532660c803c8cf015906c78e9608d293abd1f03d03f4457e",
        "0x80ac934070ca9d49d935fd1b59db4e7c72bb07627ed2404ee29994109a3bce0a",
        "0x5da8711c95b0ffd66a34bb075e018dd4dbdeb69eb027d4034ccd61507aa0e8ef",
        "0xccfb0b3c815e330ee54778a70e8d7f87e44f503b7eaeca5d49eb8c7ca1e94d07",
        "0x2893fee57e45d4193fb7faef56c44b4073991a290b47ec01df41a4095da732c8",
        "0xd12d948e81d0065e3b3f4da363cde94d955403b33c3b8c413d579e83b290b2f9",
        "0x7363978f57b80e43bfa1f680cbde29e395e282dcb260f83564a9479c0d6d9043",
        "0x04c2fddec950d586658f95d9bc5a119cff17c4b4674121bba119b3a9141aa8d2",
        "0x3468842a38b3bbadfb6fee7ae9d7f1905399864a04b728cae5459cf285d1ab04",
        "0xd1e53710afc9cde2aff165a5e051f872d06b7fdaa7472d69d3b4e4dc06a18314",
        "0x4b00b3a617b29e6a6ee2da22d6ccc84e4b80e764b7cde43bcb35fd5b6c54e56c",
        "0x1e3d07b3b5e03b319b19427882c978b1e1abf57773f2c38d42070e5a9698532d",
        "0x072d7abbcb09ed45e0b66da3e4e6a3d8711f8f340deb185fb23dfd54e4ea857d",
        "0x0e0886bb93300886b22eece04baaec3ad3aa21a356fc663f0906f3a224241eb2",
        "0x1881245891db70d5c70a3b47c7b1ade606372f258612c361c85210e32f7aabbc",
        "0xdbc932378933e6c8210b5a63461926b3ddc51a450b7ede2261fff9e610d351e1",
        "0xa199de162d8bbcc2968d1e8666d19900e846db6624a3ec0189ed482257950f5a",
        "0xe32c94a81472a193adcdb6fd747382efb16fa03dec170c5618db5e4e8ff14ff3",
        "0xb157437688533fa8effb32b1fa2decb068acb40cde29e02961f92f29f49a0683"
    ],
    "transactionsRoot": "0x56f32aeb5d8d992f0551f4fca41cde702a676bf95fea3351ecd013e7691b90c2",
    "uncles": [],
    "withdrawals": [],
    "withdrawalsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"
}
```

### LINKED ISSUE #2139: [Feature] Add manual helper deserde for pending block
### Component

rpc

### Describe the feature you would like

ref #2117

for some reasons client remove fields from the rpc response for pending block.

this is very inconvenient because we would need to
a) make those optional
b) use a different type for pending block

instead we can use manual deserde for the pending block and use default values when we deserialize the block

## TODO
* add manual helper deserde function for rpc Block and Header rpc types that use default values if those fields are missing

we only want this for the pending block so we need to check this when we send the getBlock request and deserialize accordingly

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yash-atreya**
## Motivation

Closes #2117 
Closes #2139 

## Solution

- Add new variant `PendingBlock` for fetching pending blocks.
- Deser to `serde_json::Value` first
- Check if any of these fields are missing/null `hash`, `miner`, `nonce`.
- If yes, set them to their respective Zero types.
- Finally, Deser to `BlockResponse` from `Value` representation

## PR Checklist

- [x] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/rpc-types-eth/src/block.rs
Comment (mattsse) [inline crates/rpc-types-eth/src/block.rs:1]: this is suboptimal because we only need this for the pending block.

we should implement this when decoding the pending block

**Review by mattsse — CHANGES_REQUESTED** [review]

File: crates/rpc-types-eth/src/block.rs
Comment (yash-atreya) [reply crates/rpc-types-eth/src/block.rs:1]: [8ca9295](https://github.com/alloy-rs/alloy/pull/2146/commits/8ca9295b97accab99a884db6674331ecae879479)

File: crates/provider/src/provider/get_block.rs [hunk 1]
```diff
@@ -101,6 +109,16 @@ where
         }
     }
 
+    /// Create a new [`EthGetBlock`] request with the given [`RpcCall`] for pending block.
+    pub fn new_pending_rpc(inner: RpcCall<EthGetBlockParams, Option<Value>>) -> Self {
+        Self {
+            block: BlockId::pending(),
+            inner: GetBlockInner::PendingBlock(inner),
+            kind: BlockTransactionsKind::Hashes,
```
Comment (mattsse) [inline crates/provider/src/provider/get_block.rs:117]: how do we know this?

File: crates/provider/src/provider/get_block.rs [hunk 2]
```diff
@@ -145,6 +163,42 @@ where
...
+                        if block.get("miner").map_or(true, |v| v.is_null())
+                            || block.get("beneficiary").map_or(true, |v| v.is_null())
+                        {
+                            block["miner"] = Value::String(format!("{}", Address::ZERO));
+                        }
+
+                        let block = serde_json::from_value(block.clone())
+                            .map_err(|e| TransportError::deser_err(e, block.to_string()))?;
+
+                        let block = utils::convert_to_hashes(Some(block));
```
[the remark this answers is not in the document]
Comment (yash-atreya) [reply crates/provider/src/provider/get_block.rs]: [3f1961d](https://github.com/alloy-rs/alloy/pull/2146/commits/3f1961dee0eb4d2a126fa8c9811e1f5efb7aa1a5)

**Review by mattsse — APPROVED** [review]
great!
