### PR TITLE
fix: normalize recovery bytes in flashbots signature

### LINKED ISSUE #3191: [Bug] Inconsistent signature handling for sign_flashbots_payload
### Component

consensus, eips, genesis

### What version of Alloy are you on?

1.1.1

### Operating System

None

### Describe the bug

`alloy_primitives::Signature` normalizes the recovery ID as soon as it’s created (`Signature::from_raw_array` calls `normalize_v`). Internally it keeps `v` as a boolean `y-parity`, and every recovery path (`recover_signer`) rebuilds the [r || s || v] array by copying r, s, and writing signature.v() as u8. The canonical way here is always to feed a `v ∈ {0,1}` into libsecp256k1 (also matching go-ethereum’s `SigToPub`).

In `crates/provider/src/ext/mev/with_auth.rs`, `sign_flashbots_payload` takes the signer output and immediately calls `signature.as_bytes()`. That accessor is for RLP/EIP-155 encoding, so it writes `v = 27 + parity` (see `Signature::as_bytes`). 

## Impact
The flashbots signature does not follow the canonical encoding. The server may use `recover_signer` (in rust) or geth's `crypto.SigToPub` to recover the pubkey. However both handlers do not accept the signature generated by `sign_flashbots_payload`.

## Fix
replace `message_hash.as_bytes()` in `sign_flashbots_payload` with correct `y-parity`.
```rust
let signature = signer.sign_message(...).await?;
let mut sig_bytes = [0u8; 65];
sig_bytes[..32].copy_from_slice(&signature.r().to_be_bytes::<32>());
sig_bytes[32..64].copy_from_slice(&signature.s().to_be_bytes::<32>());
sig_bytes[64] = signature.v() as u8;
hex::encode_prefixed(sig_bytes);
```

### PR DESCRIPTION
**Pull request by 0xJchen**
This PR changes the signature encoding in `sign_flashbots_payload` to meet the canonical way of formatting sigs. It serializes flashbots signatures with a normalized recovery byte (`v = 0/1`), instead of using `Signature::as_bytes()`, which produced legacy 27/28 values

Fixes #3191

### CODE REVIEW

File: crates/provider/src/ext/mev/with_auth.rs [hunk 1]
```diff
@@ -122,7 +122,13 @@ pub async fn sign_flashbots_payload<S: Signer + Send + Sync>(
 ) -> Result<String, alloy_signer::Error> {
     let message_hash = keccak256(body.as_bytes()).to_string();
     let signature = signer.sign_message(message_hash.as_bytes()).await?;
-    Ok(format!("{}:{}", signer.address(), hex::encode_prefixed(signature.as_bytes())))
+
+    // Normalized recovery byte (0/1) following the canonical signature encoding
+    let mut sig_bytes = [0u8; 65];
+    sig_bytes[..32].copy_from_slice(&signature.r().to_be_bytes::<32>());
+    sig_bytes[32..64].copy_from_slice(&signature.s().to_be_bytes::<32>());
+    sig_bytes[64] = signature.v() as u8;
```
Comment (mattsse) [inline crates/provider/src/ext/mev/with_auth.rs:130]: I see, I feel like want this as a function natively on Signature as well

cc @cakevm

**Comment by cakevm** [comment]
Makes sense to me as well. I learned that `recover_signer` just works with both 27/28 and 0/1. In the Flashbots codebase I found they normalize it e.g. [here](https://github.com/flashbots/rpc-endpoint/blob/a7e8aa9beb22eb89bde8d60b87d3adbf6739b572/adapters/flashbots/signature.go#L38) for golang. So I am here in favour to follow the standard and include this PR. 
I also tested it with the current Flashbots/Buildernet RPC and it is accepted as valid.

PS: @0xJchen you may like to check the test `test_sign_flashbots_payload`, it should now end with 00 not 1b=27.

File: crates/provider/src/ext/mev/with_auth.rs (hunk 1 above)
Comment (cakevm) [reply crates/provider/src/ext/mev/with_auth.rs:130]: Yep, it would be great if there is a fn in `Signature` for this
